version: "3"
services:
  caddy:
    #image: caddy:latest
    user: 1000:1000
    #command: tail -f /dev/null
    build:
      context: .
      dockerfile: Dockerfile
    container_name: caddy
    ports:
      - 80:80 
      - 444:443 
      - 443:443
    volumes: 
      - ${PWD}/caddy/data:/data
      - ${PWD}/caddy/config:/config
      - ${PWD}/caddy/Caddyfile:/etc/caddy/Caddyfile
    network_mode: host
    restart: unless-stopped
